include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
    - eol_at_end_of_file

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/**/*.mocks.dart
